#!/bin/sh

$CMAKE -G Ninja \
  -C $SRCDIR/clang/cmake/caches/VectorEngine.cmake \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DLLVM_PARALLEL_COMPILE_JOBS=$COMPILE_THREADS \
  -DLLVM_PARALLEL_LINK_JOBS=$LINK_THREADS \
  -DCMAKE_INSTALL_PREFIX=$DEST \
  -DCMAKE_C_FLAGS="$OPTFLAGS" \
  -DCMAKE_CXX_FLAGS="$OPTFLAGS" \
  -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
  $SRCDIR/llvm
