#!/bin/sh

$CMAKE -G Ninja \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DLLVM_TARGETS_TO_BUILD="$TARGET" \
  -DCMAKE_INSTALL_PREFIX=$DEST \
  -DLLVM_ENABLE_CXX1Y=on \
  -DLLVM_ENABLE_ASSERTIONS=on \
  -DBUILD_SHARED_LIBS=on \
  -DRV_ENABLE_SLEEF=on \
  -DRV_ENABLE_CRT=on \
  -DRV_ENABLE_VP=on \
  $SRCDIR/llvm
